import Head from 'next/head'
import styles from '../styles/Home.module.css'

// SubPages
import Footer from "../subpages/Footer";
import Iframe from "../subpages/Iframe";
import Faq from "../subpages/PerguntasFrequentes";
import Topo from "../subpages/Topo";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Batida de Ponto - G4F</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/g4f.svg" />
      </Head>

        <div className={styles.image_background}>
            <Topo/>
            <Faq/>
            <Iframe/>
            <Footer/>
        </div>
    </div >
  )
}
